export const students = [
  {
    id: 1,
    name: "Abror",
    age: "24",
    adress: "Daegu,Korea",
    status: "student",
    nickname: "vito",
    univ: "Yeungnam",
    job: "developer",
  },
  {
    id: 2,
    name: "Sherzod",
    age: "26",
    adress: "Seul,Korea",
    status: "student",
    nickname: "sherik",
    univ: "sejong",
    job: "junior developer",
  },
  {
    id: 3,
    name: "Rahim",
    age: "24",
    adress: "Seul,Korea",
    status: "student",
    nickname: "hoorwen",
    univ: "yeungnam",
    job: "developer",
  },
  {
    id: 4,
    name: "Sher",
    age: "29",
    adress: "Busan,Korea",
    status: "student",
    nickname: "shawn",
    univ: "Busan national",
    job: "middle developer",
  },
  {
    id: 5,
    name: "Fazik",
    age: "28",
    adress: "Daegu,Korea",
    status: "worker",
    nickname: "dean",
    univ: "KNU",
    job: "senior developer",
  },
];
